config/routes.rb
Rails.application.routes.draw do

  root    'pages#index', as: 'home'

  # PAGES
  get     'about' =>  'pages#about'

  # USERS
  get     '/signup', to: 'users#new'
  post    '/signup', to: 'users#create'
  resources :users

  # SESSIONS
  get     '/login', to: 'sessions#new'
  post    '/login', to: 'sessions#create'
  get     '/logout', to: 'sessions#destroy'

  # COMMENTS / Rails gen routes
  # get 'pages/index'
  # get 'pages/about'
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord

   has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   include ApplicationHelper

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
    if !logged_in?
        redirect_to login_path
    end
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    if logged_in?
      redirect_to home_path      
    end
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to home_path
    else
      render :new
    end
  end

  def destroy
    session.delete :user_id
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   def new
      if !logged_in?
         @user = User.new
      else
         redirect_to home_path
      end
   end

   def create
      user = User.new(user_params)
      if user.save
         session[:user_id] = user.id
         redirect_to home_path   
      else
         render :new
      end
   end



   private

   def user_params
      params.require(:user).permit(:name, :email, :username, :password)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper

   def current_user
      @current_user ||= User.find_by(id: session[:user_id])
   end

   def logged_in?
      current_user
   end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
   <div class="container">
      <h1 class="logo"></h1>
      <nav>
         <ul>
            <li><%= link_to "Home", home_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Login", login_path %></li>
            <li><%= link_to "Logout", logout_path %></li>
         </ul>
        
      </nav>
   </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoleculeMaker3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

app/views/pages/index.html.erb
<h1>Home Page</h1>

app/views/users/new.html.erb
<h1>New User</h1>

<hr>
<%= form_with model: @user do |f| %>
   <%= f.label :name %>:
   <%= f.text_field :name %><br>
   <%= f.label :email %>:
   <%= f.email_field :email %><br>
   <%= f.label :username %>:
   <%= f.text_field :username %><br>
   <%= f.label :password %>:
   <%= f.password_field :password %><br>
   <%= f.submit 'Sign Up' %>
<% end %>